// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rOU5iWm6HSK8oUbTLqcvyo1jlKx2E3A',
    appId: '1:931171337875:web:3cafdcd567382c7072ef66',
    messagingSenderId: '931171337875',
    projectId: 'doctor-appointment-79455',
    authDomain: 'doctor-appointment-79455.firebaseapp.com',
    storageBucket: 'doctor-appointment-79455.appspot.com',
    measurementId: 'G-16320ER9FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClDqOG1m04YPH6aHTfyW5YLWleFtX8azI',
    appId: '1:931171337875:android:5889dbbee071af4b72ef66',
    messagingSenderId: '931171337875',
    projectId: 'doctor-appointment-79455',
    storageBucket: 'doctor-appointment-79455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB72gzH_oBJW0zoz9ZmQFiZo4Q3k3Y59Cw',
    appId: '1:931171337875:ios:75abbf2682cc987a72ef66',
    messagingSenderId: '931171337875',
    projectId: 'doctor-appointment-79455',
    storageBucket: 'doctor-appointment-79455.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB72gzH_oBJW0zoz9ZmQFiZo4Q3k3Y59Cw',
    appId: '1:931171337875:ios:75abbf2682cc987a72ef66',
    messagingSenderId: '931171337875',
    projectId: 'doctor-appointment-79455',
    storageBucket: 'doctor-appointment-79455.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2rOU5iWm6HSK8oUbTLqcvyo1jlKx2E3A',
    appId: '1:931171337875:web:92efa50a1e4ffcf872ef66',
    messagingSenderId: '931171337875',
    projectId: 'doctor-appointment-79455',
    authDomain: 'doctor-appointment-79455.firebaseapp.com',
    storageBucket: 'doctor-appointment-79455.appspot.com',
    measurementId: 'G-E9PPK63QQD',
  );

}